package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaTaller generated by hbm2java
 */
public class CategoriaTaller  implements java.io.Serializable {


     private int idCategoriaTaller;
     private String nombre;
     private Set<Taller> tallers = new HashSet<Taller>(0);

    public CategoriaTaller() {
    }

	
    public CategoriaTaller(int idCategoriaTaller, String nombre) {
        this.idCategoriaTaller = idCategoriaTaller;
        this.nombre = nombre;
    }
    public CategoriaTaller(int idCategoriaTaller, String nombre, Set<Taller> tallers) {
       this.idCategoriaTaller = idCategoriaTaller;
       this.nombre = nombre;
       this.tallers = tallers;
    }
   
    public int getIdCategoriaTaller() {
        return this.idCategoriaTaller;
    }
    
    public void setIdCategoriaTaller(int idCategoriaTaller) {
        this.idCategoriaTaller = idCategoriaTaller;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Taller> getTallers() {
        return this.tallers;
    }
    
    public void setTallers(Set<Taller> tallers) {
        this.tallers = tallers;
    }




}


