package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CentroEducativo generated by hbm2java
 */
public class CentroEducativo  implements java.io.Serializable {


     private int idCentroEducativo;
     private CentroPoblado centroPoblado;
     private TurnoAtencion turnoAtencion;
     private Ugel ugel;
     private Usuario usuario;
     private String nombre;
     private String codLocal;
     private String formaAtencion;
     private String tipoEnsenanza;
     private String tipoSexo;
     private String gestion;
     private String dependencia;
     private Integer telefono;
     private String correoElectronico;
     private String url;
     private String tipoArea;
     private boolean disCrecer;
     private boolean disVraem;
     private boolean disJuntos;
     private BigDecimal latitud;
     private BigDecimal longitud;
     private boolean estado;
     private int numAlumHombre;
     private int numAlumMujer;
     private int numAlumTotal;
     private int numDocente;
     private int numSeccion;
     private Integer numAulaSeccion;
     private Integer numCampoDeportivo;
     private String tipoDatos;
     private String director;
     private Set<Comentario> comentarios = new HashSet<Comentario>(0);
     private Set<CentroEducativoCurso> centroEducativoCursos = new HashSet<CentroEducativoCurso>(0);
     private Set<CentroEducativoIdioma> centroEducativoIdiomas = new HashSet<CentroEducativoIdioma>(0);
     private Set<CentroEducativoTaller> centroEducativoTallers = new HashSet<CentroEducativoTaller>(0);

    public CentroEducativo() {
    }

	
    public CentroEducativo(int idCentroEducativo, CentroPoblado centroPoblado, TurnoAtencion turnoAtencion, Ugel ugel, String nombre, String codLocal, String formaAtencion, String tipoEnsenanza, String tipoSexo, String gestion, String dependencia, String tipoArea, boolean disCrecer, boolean disVraem, boolean disJuntos, boolean estado, int numAlumHombre, int numAlumMujer, int numAlumTotal, int numDocente, int numSeccion, String tipoDatos) {
        this.idCentroEducativo = idCentroEducativo;
        this.centroPoblado = centroPoblado;
        this.turnoAtencion = turnoAtencion;
        this.ugel = ugel;
        this.nombre = nombre;
        this.codLocal = codLocal;
        this.formaAtencion = formaAtencion;
        this.tipoEnsenanza = tipoEnsenanza;
        this.tipoSexo = tipoSexo;
        this.gestion = gestion;
        this.dependencia = dependencia;
        this.tipoArea = tipoArea;
        this.disCrecer = disCrecer;
        this.disVraem = disVraem;
        this.disJuntos = disJuntos;
        this.estado = estado;
        this.numAlumHombre = numAlumHombre;
        this.numAlumMujer = numAlumMujer;
        this.numAlumTotal = numAlumTotal;
        this.numDocente = numDocente;
        this.numSeccion = numSeccion;
        this.tipoDatos = tipoDatos;
    }
    public CentroEducativo(int idCentroEducativo, CentroPoblado centroPoblado, TurnoAtencion turnoAtencion, Ugel ugel, Usuario usuario, String nombre, String codLocal, String formaAtencion, String tipoEnsenanza, String tipoSexo, String gestion, String dependencia, Integer telefono, String correoElectronico, String url, String tipoArea, boolean disCrecer, boolean disVraem, boolean disJuntos, BigDecimal latitud, BigDecimal longitud, boolean estado, int numAlumHombre, int numAlumMujer, int numAlumTotal, int numDocente, int numSeccion, Integer numAulaSeccion, Integer numCampoDeportivo, String tipoDatos, String director, Set<Comentario> comentarios, Set<CentroEducativoCurso> centroEducativoCursos, Set<CentroEducativoIdioma> centroEducativoIdiomas, Set<CentroEducativoTaller> centroEducativoTallers) {
       this.idCentroEducativo = idCentroEducativo;
       this.centroPoblado = centroPoblado;
       this.turnoAtencion = turnoAtencion;
       this.ugel = ugel;
       this.usuario = usuario;
       this.nombre = nombre;
       this.codLocal = codLocal;
       this.formaAtencion = formaAtencion;
       this.tipoEnsenanza = tipoEnsenanza;
       this.tipoSexo = tipoSexo;
       this.gestion = gestion;
       this.dependencia = dependencia;
       this.telefono = telefono;
       this.correoElectronico = correoElectronico;
       this.url = url;
       this.tipoArea = tipoArea;
       this.disCrecer = disCrecer;
       this.disVraem = disVraem;
       this.disJuntos = disJuntos;
       this.latitud = latitud;
       this.longitud = longitud;
       this.estado = estado;
       this.numAlumHombre = numAlumHombre;
       this.numAlumMujer = numAlumMujer;
       this.numAlumTotal = numAlumTotal;
       this.numDocente = numDocente;
       this.numSeccion = numSeccion;
       this.numAulaSeccion = numAulaSeccion;
       this.numCampoDeportivo = numCampoDeportivo;
       this.tipoDatos = tipoDatos;
       this.director = director;
       this.comentarios = comentarios;
       this.centroEducativoCursos = centroEducativoCursos;
       this.centroEducativoIdiomas = centroEducativoIdiomas;
       this.centroEducativoTallers = centroEducativoTallers;
    }
   
    public int getIdCentroEducativo() {
        return this.idCentroEducativo;
    }
    
    public void setIdCentroEducativo(int idCentroEducativo) {
        this.idCentroEducativo = idCentroEducativo;
    }
    public CentroPoblado getCentroPoblado() {
        return this.centroPoblado;
    }
    
    public void setCentroPoblado(CentroPoblado centroPoblado) {
        this.centroPoblado = centroPoblado;
    }
    public TurnoAtencion getTurnoAtencion() {
        return this.turnoAtencion;
    }
    
    public void setTurnoAtencion(TurnoAtencion turnoAtencion) {
        this.turnoAtencion = turnoAtencion;
    }
    public Ugel getUgel() {
        return this.ugel;
    }
    
    public void setUgel(Ugel ugel) {
        this.ugel = ugel;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodLocal() {
        return this.codLocal;
    }
    
    public void setCodLocal(String codLocal) {
        this.codLocal = codLocal;
    }
    public String getFormaAtencion() {
        return this.formaAtencion;
    }
    
    public void setFormaAtencion(String formaAtencion) {
        this.formaAtencion = formaAtencion;
    }
    public String getTipoEnsenanza() {
        return this.tipoEnsenanza;
    }
    
    public void setTipoEnsenanza(String tipoEnsenanza) {
        this.tipoEnsenanza = tipoEnsenanza;
    }
    public String getTipoSexo() {
        return this.tipoSexo;
    }
    
    public void setTipoSexo(String tipoSexo) {
        this.tipoSexo = tipoSexo;
    }
    public String getGestion() {
        return this.gestion;
    }
    
    public void setGestion(String gestion) {
        this.gestion = gestion;
    }
    public String getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(String dependencia) {
        this.dependencia = dependencia;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getTipoArea() {
        return this.tipoArea;
    }
    
    public void setTipoArea(String tipoArea) {
        this.tipoArea = tipoArea;
    }
    public boolean isDisCrecer() {
        return this.disCrecer;
    }
    
    public void setDisCrecer(boolean disCrecer) {
        this.disCrecer = disCrecer;
    }
    public boolean isDisVraem() {
        return this.disVraem;
    }
    
    public void setDisVraem(boolean disVraem) {
        this.disVraem = disVraem;
    }
    public boolean isDisJuntos() {
        return this.disJuntos;
    }
    
    public void setDisJuntos(boolean disJuntos) {
        this.disJuntos = disJuntos;
    }
    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }
    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public int getNumAlumHombre() {
        return this.numAlumHombre;
    }
    
    public void setNumAlumHombre(int numAlumHombre) {
        this.numAlumHombre = numAlumHombre;
    }
    public int getNumAlumMujer() {
        return this.numAlumMujer;
    }
    
    public void setNumAlumMujer(int numAlumMujer) {
        this.numAlumMujer = numAlumMujer;
    }
    public int getNumAlumTotal() {
        return this.numAlumTotal;
    }
    
    public void setNumAlumTotal(int numAlumTotal) {
        this.numAlumTotal = numAlumTotal;
    }
    public int getNumDocente() {
        return this.numDocente;
    }
    
    public void setNumDocente(int numDocente) {
        this.numDocente = numDocente;
    }
    public int getNumSeccion() {
        return this.numSeccion;
    }
    
    public void setNumSeccion(int numSeccion) {
        this.numSeccion = numSeccion;
    }
    public Integer getNumAulaSeccion() {
        return this.numAulaSeccion;
    }
    
    public void setNumAulaSeccion(Integer numAulaSeccion) {
        this.numAulaSeccion = numAulaSeccion;
    }
    public Integer getNumCampoDeportivo() {
        return this.numCampoDeportivo;
    }
    
    public void setNumCampoDeportivo(Integer numCampoDeportivo) {
        this.numCampoDeportivo = numCampoDeportivo;
    }
    public String getTipoDatos() {
        return this.tipoDatos;
    }
    
    public void setTipoDatos(String tipoDatos) {
        this.tipoDatos = tipoDatos;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public Set<Comentario> getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set<Comentario> comentarios) {
        this.comentarios = comentarios;
    }
    public Set<CentroEducativoCurso> getCentroEducativoCursos() {
        return this.centroEducativoCursos;
    }
    
    public void setCentroEducativoCursos(Set<CentroEducativoCurso> centroEducativoCursos) {
        this.centroEducativoCursos = centroEducativoCursos;
    }
    public Set<CentroEducativoIdioma> getCentroEducativoIdiomas() {
        return this.centroEducativoIdiomas;
    }
    
    public void setCentroEducativoIdiomas(Set<CentroEducativoIdioma> centroEducativoIdiomas) {
        this.centroEducativoIdiomas = centroEducativoIdiomas;
    }
    public Set<CentroEducativoTaller> getCentroEducativoTallers() {
        return this.centroEducativoTallers;
    }
    
    public void setCentroEducativoTallers(Set<CentroEducativoTaller> centroEducativoTallers) {
        this.centroEducativoTallers = centroEducativoTallers;
    }




}


