package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1



/**
 * CentroEducativoCurso generated by hbm2java
 */
public class CentroEducativoCurso  implements java.io.Serializable {


     private int idCentroEducativoCurso;
     private CentroEducativo centroEducativo;
     private Curso curso;

    public CentroEducativoCurso() {
    }

    public CentroEducativoCurso(int idCentroEducativoCurso, CentroEducativo centroEducativo, Curso curso) {
       this.idCentroEducativoCurso = idCentroEducativoCurso;
       this.centroEducativo = centroEducativo;
       this.curso = curso;
    }
   
    public int getIdCentroEducativoCurso() {
        return this.idCentroEducativoCurso;
    }
    
    public void setIdCentroEducativoCurso(int idCentroEducativoCurso) {
        this.idCentroEducativoCurso = idCentroEducativoCurso;
    }
    public CentroEducativo getCentroEducativo() {
        return this.centroEducativo;
    }
    
    public void setCentroEducativo(CentroEducativo centroEducativo) {
        this.centroEducativo = centroEducativo;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }




}


