package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1



/**
 * CentroEducativoIdioma generated by hbm2java
 */
public class CentroEducativoIdioma  implements java.io.Serializable {


     private int idCentroEducativoIdioma;
     private CentroEducativo centroEducativo;
     private Idioma idioma;
     private Boolean principal;

    public CentroEducativoIdioma() {
    }

	
    public CentroEducativoIdioma(int idCentroEducativoIdioma, CentroEducativo centroEducativo, Idioma idioma) {
        this.idCentroEducativoIdioma = idCentroEducativoIdioma;
        this.centroEducativo = centroEducativo;
        this.idioma = idioma;
    }
    public CentroEducativoIdioma(int idCentroEducativoIdioma, CentroEducativo centroEducativo, Idioma idioma, Boolean principal) {
       this.idCentroEducativoIdioma = idCentroEducativoIdioma;
       this.centroEducativo = centroEducativo;
       this.idioma = idioma;
       this.principal = principal;
    }
   
    public int getIdCentroEducativoIdioma() {
        return this.idCentroEducativoIdioma;
    }
    
    public void setIdCentroEducativoIdioma(int idCentroEducativoIdioma) {
        this.idCentroEducativoIdioma = idCentroEducativoIdioma;
    }
    public CentroEducativo getCentroEducativo() {
        return this.centroEducativo;
    }
    
    public void setCentroEducativo(CentroEducativo centroEducativo) {
        this.centroEducativo = centroEducativo;
    }
    public Idioma getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(Idioma idioma) {
        this.idioma = idioma;
    }
    public Boolean getPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(Boolean principal) {
        this.principal = principal;
    }




}


