package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1



/**
 * CentroEducativoTaller generated by hbm2java
 */
public class CentroEducativoTaller  implements java.io.Serializable {


     private int idCentroEducatiboTaller;
     private CentroEducativo centroEducativo;
     private Taller taller;

    public CentroEducativoTaller() {
    }

    public CentroEducativoTaller(int idCentroEducatiboTaller, CentroEducativo centroEducativo, Taller taller) {
       this.idCentroEducatiboTaller = idCentroEducatiboTaller;
       this.centroEducativo = centroEducativo;
       this.taller = taller;
    }
   
    public int getIdCentroEducatiboTaller() {
        return this.idCentroEducatiboTaller;
    }
    
    public void setIdCentroEducatiboTaller(int idCentroEducatiboTaller) {
        this.idCentroEducatiboTaller = idCentroEducatiboTaller;
    }
    public CentroEducativo getCentroEducativo() {
        return this.centroEducativo;
    }
    
    public void setCentroEducativo(CentroEducativo centroEducativo) {
        this.centroEducativo = centroEducativo;
    }
    public Taller getTaller() {
        return this.taller;
    }
    
    public void setTaller(Taller taller) {
        this.taller = taller;
    }




}


