package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CentroPoblado generated by hbm2java
 */
public class CentroPoblado  implements java.io.Serializable {


     private int idCentroPoblado;
     private Distrito distrito;
     private String nombre;
     private Set<CentroEducativo> centroEducativos = new HashSet<CentroEducativo>(0);

    public CentroPoblado() {
    }

	
    public CentroPoblado(int idCentroPoblado, Distrito distrito, String nombre) {
        this.idCentroPoblado = idCentroPoblado;
        this.distrito = distrito;
        this.nombre = nombre;
    }
    public CentroPoblado(int idCentroPoblado, Distrito distrito, String nombre, Set<CentroEducativo> centroEducativos) {
       this.idCentroPoblado = idCentroPoblado;
       this.distrito = distrito;
       this.nombre = nombre;
       this.centroEducativos = centroEducativos;
    }
   
    public int getIdCentroPoblado() {
        return this.idCentroPoblado;
    }
    
    public void setIdCentroPoblado(int idCentroPoblado) {
        this.idCentroPoblado = idCentroPoblado;
    }
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<CentroEducativo> getCentroEducativos() {
        return this.centroEducativos;
    }
    
    public void setCentroEducativos(Set<CentroEducativo> centroEducativos) {
        this.centroEducativos = centroEducativos;
    }




}


