package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int idComentario;
     private CentroEducativo centroEducativo;
     private Usuario usuario;
     private String detalle;
     private Date fecha;

    public Comentario() {
    }

    public Comentario(int idComentario, CentroEducativo centroEducativo, Usuario usuario, String detalle, Date fecha) {
       this.idComentario = idComentario;
       this.centroEducativo = centroEducativo;
       this.usuario = usuario;
       this.detalle = detalle;
       this.fecha = fecha;
    }
   
    public int getIdComentario() {
        return this.idComentario;
    }
    
    public void setIdComentario(int idComentario) {
        this.idComentario = idComentario;
    }
    public CentroEducativo getCentroEducativo() {
        return this.centroEducativo;
    }
    
    public void setCentroEducativo(CentroEducativo centroEducativo) {
        this.centroEducativo = centroEducativo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


