package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private String nombre;
     private Set<Provincia> provincias = new HashSet<Provincia>(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Departamento(int idDepartamento, String nombre, Set<Provincia> provincias) {
       this.idDepartamento = idDepartamento;
       this.nombre = nombre;
       this.provincias = provincias;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Provincia> getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set<Provincia> provincias) {
        this.provincias = provincias;
    }




}


