package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Distrito generated by hbm2java
 */
public class Distrito  implements java.io.Serializable {


     private int idDistrito;
     private Provincia provincia;
     private String nombe;
     private Set<CentroPoblado> centroPoblados = new HashSet<CentroPoblado>(0);

    public Distrito() {
    }

	
    public Distrito(int idDistrito, Provincia provincia, String nombe) {
        this.idDistrito = idDistrito;
        this.provincia = provincia;
        this.nombe = nombe;
    }
    public Distrito(int idDistrito, Provincia provincia, String nombe, Set<CentroPoblado> centroPoblados) {
       this.idDistrito = idDistrito;
       this.provincia = provincia;
       this.nombe = nombe;
       this.centroPoblados = centroPoblados;
    }
   
    public int getIdDistrito() {
        return this.idDistrito;
    }
    
    public void setIdDistrito(int idDistrito) {
        this.idDistrito = idDistrito;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombe() {
        return this.nombe;
    }
    
    public void setNombe(String nombe) {
        this.nombe = nombe;
    }
    public Set<CentroPoblado> getCentroPoblados() {
        return this.centroPoblados;
    }
    
    public void setCentroPoblados(Set<CentroPoblado> centroPoblados) {
        this.centroPoblados = centroPoblados;
    }




}


