package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Idioma generated by hbm2java
 */
public class Idioma  implements java.io.Serializable {


     private int idIdioma;
     private String nombre;
     private Set<CentroEducativoIdioma> centroEducativoIdiomas = new HashSet<CentroEducativoIdioma>(0);

    public Idioma() {
    }

	
    public Idioma(int idIdioma, String nombre) {
        this.idIdioma = idIdioma;
        this.nombre = nombre;
    }
    public Idioma(int idIdioma, String nombre, Set<CentroEducativoIdioma> centroEducativoIdiomas) {
       this.idIdioma = idIdioma;
       this.nombre = nombre;
       this.centroEducativoIdiomas = centroEducativoIdiomas;
    }
   
    public int getIdIdioma() {
        return this.idIdioma;
    }
    
    public void setIdIdioma(int idIdioma) {
        this.idIdioma = idIdioma;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<CentroEducativoIdioma> getCentroEducativoIdiomas() {
        return this.centroEducativoIdiomas;
    }
    
    public void setCentroEducativoIdiomas(Set<CentroEducativoIdioma> centroEducativoIdiomas) {
        this.centroEducativoIdiomas = centroEducativoIdiomas;
    }




}


