package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private TipoPersona tipoPersona;
     private String nombre;
     private String apellidoPat;
     private String apellidoMat;
     private Date fechaNac;
     private String sexo;
     private String correoElectronico;
     private Integer telefono;
     private String direccion;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Persona() {
    }

	
    public Persona(int idPersona, TipoPersona tipoPersona, String nombre, String correoElectronico) {
        this.idPersona = idPersona;
        this.tipoPersona = tipoPersona;
        this.nombre = nombre;
        this.correoElectronico = correoElectronico;
    }
    public Persona(int idPersona, TipoPersona tipoPersona, String nombre, String apellidoPat, String apellidoMat, Date fechaNac, String sexo, String correoElectronico, Integer telefono, String direccion, Set<Usuario> usuarios) {
       this.idPersona = idPersona;
       this.tipoPersona = tipoPersona;
       this.nombre = nombre;
       this.apellidoPat = apellidoPat;
       this.apellidoMat = apellidoMat;
       this.fechaNac = fechaNac;
       this.sexo = sexo;
       this.correoElectronico = correoElectronico;
       this.telefono = telefono;
       this.direccion = direccion;
       this.usuarios = usuarios;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public TipoPersona getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(TipoPersona tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPat() {
        return this.apellidoPat;
    }
    
    public void setApellidoPat(String apellidoPat) {
        this.apellidoPat = apellidoPat;
    }
    public String getApellidoMat() {
        return this.apellidoMat;
    }
    
    public void setApellidoMat(String apellidoMat) {
        this.apellidoMat = apellidoMat;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


