package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private int idProvincia;
     private Departamento departamento;
     private String nombre;
     private Set<Distrito> distritos = new HashSet<Distrito>(0);

    public Provincia() {
    }

	
    public Provincia(int idProvincia, Departamento departamento) {
        this.idProvincia = idProvincia;
        this.departamento = departamento;
    }
    public Provincia(int idProvincia, Departamento departamento, String nombre, Set<Distrito> distritos) {
       this.idProvincia = idProvincia;
       this.departamento = departamento;
       this.nombre = nombre;
       this.distritos = distritos;
    }
   
    public int getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(int idProvincia) {
        this.idProvincia = idProvincia;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Distrito> getDistritos() {
        return this.distritos;
    }
    
    public void setDistritos(Set<Distrito> distritos) {
        this.distritos = distritos;
    }




}


