package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Taller generated by hbm2java
 */
public class Taller  implements java.io.Serializable {


     private int idTaller;
     private CategoriaTaller categoriaTaller;
     private String nombre;
     private String detalle;
     private Set<CentroEducativoTaller> centroEducativoTallers = new HashSet<CentroEducativoTaller>(0);

    public Taller() {
    }

	
    public Taller(int idTaller, CategoriaTaller categoriaTaller) {
        this.idTaller = idTaller;
        this.categoriaTaller = categoriaTaller;
    }
    public Taller(int idTaller, CategoriaTaller categoriaTaller, String nombre, String detalle, Set<CentroEducativoTaller> centroEducativoTallers) {
       this.idTaller = idTaller;
       this.categoriaTaller = categoriaTaller;
       this.nombre = nombre;
       this.detalle = detalle;
       this.centroEducativoTallers = centroEducativoTallers;
    }
   
    public int getIdTaller() {
        return this.idTaller;
    }
    
    public void setIdTaller(int idTaller) {
        this.idTaller = idTaller;
    }
    public CategoriaTaller getCategoriaTaller() {
        return this.categoriaTaller;
    }
    
    public void setCategoriaTaller(CategoriaTaller categoriaTaller) {
        this.categoriaTaller = categoriaTaller;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Set<CentroEducativoTaller> getCentroEducativoTallers() {
        return this.centroEducativoTallers;
    }
    
    public void setCentroEducativoTallers(Set<CentroEducativoTaller> centroEducativoTallers) {
        this.centroEducativoTallers = centroEducativoTallers;
    }




}


