package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPersona generated by hbm2java
 */
public class TipoPersona  implements java.io.Serializable {


     private int idTipoPersona;
     private String nombreTipo;
     private String documento;
     private Integer numeroDocumento;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public TipoPersona() {
    }

	
    public TipoPersona(int idTipoPersona) {
        this.idTipoPersona = idTipoPersona;
    }
    public TipoPersona(int idTipoPersona, String nombreTipo, String documento, Integer numeroDocumento, Set<Persona> personas) {
       this.idTipoPersona = idTipoPersona;
       this.nombreTipo = nombreTipo;
       this.documento = documento;
       this.numeroDocumento = numeroDocumento;
       this.personas = personas;
    }
   
    public int getIdTipoPersona() {
        return this.idTipoPersona;
    }
    
    public void setIdTipoPersona(int idTipoPersona) {
        this.idTipoPersona = idTipoPersona;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public Integer getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(Integer numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


