package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TurnoAtencion generated by hbm2java
 */
public class TurnoAtencion  implements java.io.Serializable {


     private int idTurnoAtencion;
     private String nombre;
     private String codTurno;
     private Set<CentroEducativo> centroEducativos = new HashSet<CentroEducativo>(0);

    public TurnoAtencion() {
    }

	
    public TurnoAtencion(int idTurnoAtencion, String nombre, String codTurno) {
        this.idTurnoAtencion = idTurnoAtencion;
        this.nombre = nombre;
        this.codTurno = codTurno;
    }
    public TurnoAtencion(int idTurnoAtencion, String nombre, String codTurno, Set<CentroEducativo> centroEducativos) {
       this.idTurnoAtencion = idTurnoAtencion;
       this.nombre = nombre;
       this.codTurno = codTurno;
       this.centroEducativos = centroEducativos;
    }
   
    public int getIdTurnoAtencion() {
        return this.idTurnoAtencion;
    }
    
    public void setIdTurnoAtencion(int idTurnoAtencion) {
        this.idTurnoAtencion = idTurnoAtencion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodTurno() {
        return this.codTurno;
    }
    
    public void setCodTurno(String codTurno) {
        this.codTurno = codTurno;
    }
    public Set<CentroEducativo> getCentroEducativos() {
        return this.centroEducativos;
    }
    
    public void setCentroEducativos(Set<CentroEducativo> centroEducativos) {
        this.centroEducativos = centroEducativos;
    }




}


