package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ugel generated by hbm2java
 */
public class Ugel  implements java.io.Serializable {


     private int idUgel;
     private String nombre;
     private Set<CentroEducativo> centroEducativos = new HashSet<CentroEducativo>(0);

    public Ugel() {
    }

	
    public Ugel(int idUgel, String nombre) {
        this.idUgel = idUgel;
        this.nombre = nombre;
    }
    public Ugel(int idUgel, String nombre, Set<CentroEducativo> centroEducativos) {
       this.idUgel = idUgel;
       this.nombre = nombre;
       this.centroEducativos = centroEducativos;
    }
   
    public int getIdUgel() {
        return this.idUgel;
    }
    
    public void setIdUgel(int idUgel) {
        this.idUgel = idUgel;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<CentroEducativo> getCentroEducativos() {
        return this.centroEducativos;
    }
    
    public void setCentroEducativos(Set<CentroEducativo> centroEducativos) {
        this.centroEducativos = centroEducativos;
    }




}


