package com.pojos;
// Generated 22-sep-2016 0:33:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Persona persona;
     private TipoUsuario tipoUsuario;
     private String nombre;
     private String contrasena;
     private Set<Comentario> comentarios = new HashSet<Comentario>(0);
     private Set<CentroEducativo> centroEducativos = new HashSet<CentroEducativo>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, TipoUsuario tipoUsuario, String nombre, String contrasena) {
        this.idUsuario = idUsuario;
        this.tipoUsuario = tipoUsuario;
        this.nombre = nombre;
        this.contrasena = contrasena;
    }
    public Usuario(int idUsuario, Persona persona, TipoUsuario tipoUsuario, String nombre, String contrasena, Set<Comentario> comentarios, Set<CentroEducativo> centroEducativos) {
       this.idUsuario = idUsuario;
       this.persona = persona;
       this.tipoUsuario = tipoUsuario;
       this.nombre = nombre;
       this.contrasena = contrasena;
       this.comentarios = comentarios;
       this.centroEducativos = centroEducativos;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set<Comentario> getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set<Comentario> comentarios) {
        this.comentarios = comentarios;
    }
    public Set<CentroEducativo> getCentroEducativos() {
        return this.centroEducativos;
    }
    
    public void setCentroEducativos(Set<CentroEducativo> centroEducativos) {
        this.centroEducativos = centroEducativos;
    }




}


